### ISSUE TITLE
404 errors with WebUI v2

### ISSUE THREAD

**Issue by zarlin** [ShokoAnime/Shoko-WebUI#615]
When loading the dashboard of the WebUI v2, I get a toast with the following error:

> 404 - Rejected
> Error occured during `GET /api/v3/File?pageSize=20&includeUnrecognized=only&sortOrder=-16` (getFiles)

And when loading the settings page I get this:

> 404 - Rejected
> Error occured during `GET /api/v3/WebUI/Theme?forceRefresh=true` (getWebuiThemes)

Additionally (this may be a side-effect of the errors), all Queue counters are 0, even when files are being processed, and the "main" queue counter in the top right shows NaN.

Info:
Server version `4.2.2.0
 (58b17bd)`
WebUI version `2.0.0-dev.126`

**Comment by revam** [comment]
Revert back to the stable web UI. The daily web UI was accidentally shipped with the last three stable, and updating it will break it because of incompatibilities with the stable server.

I've attached the guide for how to safely downgrade even if the web UI itself is unusable (also available in the discord server).

### How to revert the Web UI back to a working _stable_ version 101

- Open Swagger by navigating to `http://<shoko host>:8111/swagger/index.html?urls.primaryName=3.0`.
  Be sure to replace `<shoko host>` with the IP or DNS name of your shoko entry.

- Generate an API key to use by executing `POST /api/auth`, found under the "Auth" section in Swagger.
  Press the "Try it out" button, enter your username for `user`, your password for `pass`, and `"swagger"` for `device`, and press "Execute". Copy the API key (the value of the `"apikey"` field from the response).

- Assign the API key to the `ApiKey` field under the "Authorize" menu found at the top of the page.

- Execute `GET /api/v{version}/WebUI/Update`, found under the "WebUI" section in Swagger, making sure to select `Stable` for the `channel` and input `3` for the `version`.

- Refresh the Web UI. If a normal refresh (pressing **F5**) doesn't work, then try a forced refresh (pressing **CTRL**+**F5**).

**Comment by zarlin** [comment]
Thank you for the guide, I've reverted back to the old UI and things work as they should again.

I'm looking forward to the finished WebUI v2, it looked great!
